-- create table p3 (id int key, name char (100), nation char(3));
-- create table b3 (id int key, title char(100), authors char(200), publisher_id int, copies int);
-- -- create table c3 (id int key, name char (25), rank int);
-- create table o3 (customer_id int, book_id int, quantity int);
